// clinet-vue/src/components/base/Navbar.vue
<template>
  <nav>
    <h1>
      <router-link to="/">
        <i class="fa-solid fa-code"></i>
        <span>Home</span>
      </router-link>
    </h1>
    <ul class="menu_list" v-if="isLogin">
      <li @click="logout">
        <span>로그아웃</span>
      </li>
    </ul>
    <ul class="menu_list" v-else>
      <li>
        <router-link to="/login">로그인</router-link>
      </li>
      <li>
        <router-link to="/register">회원가입</router-link>
      </li>
    </ul>
  </nav>
</template>

<script>
import store from '@/store';
import { removeToken } from '@/utils/localStoarge';

export default {
  name: 'Nav bar',
  computed: {
    isLogin() {
      return store.state.isLogin; 
    }
  },
  methods: {
    logout() {
      removeToken();
      store.commit('isLoginFalse');
    }
  },
}
</script>

<style scoped>
nav {
  background-color: #555;
  color: rgb(236, 236, 236);
  height: 70px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 20px;
  margin-bottom: 30px;
}
nav h1 span {
  margin-left: 10px;
}
.menu_list {
  display: flex;
}
.menu_list li {
  margin-left: 10px;
}
.menu_list li span {
  cursor: pointer;
}
</style>

// client-react/src/components/base/navbar.jsx
import { Link } from "react-router-dom";
import { useContext } from "react";
import { FaRegUserCircle, FaCode } from 'react-icons/fa';
import { removeToken } from '../../utils/localStorage';
import './navbar.css';
import { AppContext } from "../../App";

export default function Navbar() {
  const { isLogin, updateIsLogin } = useContext(AppContext);
  function logout() {
    removeToken();
    updateIsLogin(false);
  }
  return (
    <nav className="navbar">
      <h1>
        <Link to='/'>
          <FaCode color="#eeeeee" />
          <span>Home</span>
        </Link>
      </h1>
      {
        isLogin
        ? <div className="logout_text" onClick={logout}>
            <FaRegUserCircle />
            로그아웃
          </div>
        : <div className="menu_list">
            <Link to='/login' >로그인</Link>
            <Link to='/register' >회원가입</Link>
          </div>
      }
    </nav>
  )
}
